### ISSUE TITLE
Inconsistent Inference Application

### ISSUE THREAD

**Issue by Jmw150** [raghav198/pamplemousse#5]
Proof Mouse fails to apply inferences rules to subexpressions when from the list of deductions, but is okay with applying them in the equivalence list, such as double negation.

Code
```
R
1. P prem;
2. R \/ ~(Q \/ P) prem;
3. R \/ ((~Q) /\ (~P)) dm_oa 2;
4. R \/ (~P) simpl 3;
5. R ds 1, 4;
```
Error
```
1. P prem []    ✓                                                                                        
2. (R \/ ~(Q \/ P)) prem []     ✓                                                                        
3. (R \/ (~Q /\ ~P)) dm_oa [2]  ✓                                                                        
4. (R \/ ~P) simpl [3]  ✗                                                                                
Error: (R \/ (~Q /\ ~P)) is not a conjunction! 
```

**Comment by raghav198** [comment]
If you read the [Equivalence Rules](https://github.com/raghav198/proof-mouse?tab=readme-ov-file#equivalence-rules) section of the README, you will notice that this _exact_ behavior is both documented and expected; furthermore, its required for correctness. For instance, applying `simp` to a term of `(A /\ B) -> C` results in a term of `A -> C`, but notice that the latter is not entailed by the first. The obligation of proving that you _can_ simplify `A -> (B /\ C)` to `A -> B` exactly amounts to doing that proof manually (e.g. constructing a hypothetical world, or by the universal property of conjunction, or whatever), which is a common requirement in both Gentzen-style proofs, and this class.

**Comment by Jmw150** [comment]
It is a defined quirk of your software, not necessarily the class. A 1930's style is your preference. 

But you are right. Simplification requires extra conditions to work. My mistake.
