### ISSUE TITLE
Parser Gives Unhelpful Error Messages.

### ISSUE THREAD

**Issue by Jmw150** [raghav198/pamplemousse#6]
The parser gives incorrect and unhelpful error codes.

Code
```
B

1. N                prem;
2. R \/ ~(Q \/ P)   prem;
3. ~R -> ~(Q \/ P)  imp, 2;
```
Error
```
3. ~R -> ~(Q \/ P)  imp, 2;
^
ParseException: Expected end of text, found '3'  (at char 53), (line:4, col:1)
```
It was not the '3' of course. It was the comma after imp.

**Comment by raghav198** [comment]
Yup, this is a known issue. I will at some point get around to migrating away from the parser combinator library it currently uses. Alternatively, I would happy to accept a pull request to that effect.

________________________________
From: Engiseer ***@***.***>
Sent: Monday, March 11, 2024 10:48:23 PM
To: raghav198/proof-mouse ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [raghav198/proof-mouse] Parser Gives Unhelpful Error Messages. (Issue #6)


The parser gives incorrect and unhelpful error codes.

Code

B

1. N                prem;
2. R \/ ~(Q \/ P)   prem;
3. ~R -> ~(Q \/ P)  imp, 2;


Error

3. ~R -> ~(Q \/ P)  imp, 2;
^
ParseException: Expected end of text, found '3'  (at char 53), (line:4, col:1)


It was not the '3' of course. It was the comma after imp.
