### ISSUE TITLE
Comments Before the Conclusion are Illegal

### ISSUE THREAD

**Issue by Jmw150** [raghav198/pamplemousse#7]
Comments are not documented behavior to begin with. But this is an interesting choice.

Code
```
/* Generic Title */
B

1. N                prem;
2. R \/ ~(Q \/ P)   prem;
3. ~R -> ~(Q \/ P)  prem;
```

Error
```
/* Generic Title */
^
ParseException: Expected {{{[{{[{Forward: {{{{W:(A-Za-z) Suppress:('(') W:(A-Za-z) [{Suppress:(',') W:(A-Za-z)}]... Suppress:(')')} | (A-Z)} | {{Suppress:('(') : ...} Suppress:(')')}} | {'~' : ...}} Suppress:('/\\')}]... Forward: {{{{W:(A-Za-z) Suppress:('(') W:(A-Za-z) [{Suppress:(',') W:(A-Za-z)}]... Suppress:(')')} | (A-Z)} | {{Suppress:('(') : ...} Suppress:(')')}} | {'~' : ...}}} Suppress:('\\/')}]... {[{Forward: {{{{W:(A-Za-z) Suppress:('(') W:(A-Za-z) [{Suppress:(',') W:(A-Za-z)}]... Suppress:(')')} | (A-Z)} | {{Suppress:('(') : ...} Suppress:(')')}} | {'~' : ...}} Suppress:('/\\')}]... Forward: {{{{W:(A-Za-z) Suppress:('(') W:(A-Za-z) ...
```

**Comment by raghav198** [comment]
I'm not sure what you're asking about here, since as you mentioned, comments aren't part of the documented behavior; but regardless, see #6

**Comment by Jmw150** [comment]
You implemented comments. I do not think you created this particular behavior intentionally. So here is a potential bug to keep in mind anyway. It is fine to leave these open. Closing them means you fixed the issue.

The parse also fails if the conclusion is not the first line, such as starting with empty space at the top of the file, while the proof section is more flexible.
